In [27]:
import pandas as pd
import re

In [28]:
stn = pd.read_csv('../ghcnd-stations.csv')

In [29]:
stn['COUNTRY_CODE'] = stn['STATION'].str[0:2]
stn['STATE_CODE'] = stn['NAME'].str[0:2]
stn = stn.loc[stn['COUNTRY_CODE']=='US']
stn.head(15)

,STATION,LAT,LONG,ELEV,NAME,ZIP,COUNTRY_CODE,STATE_CODE
52607,US009052008,43.7333,-96.6333,482.0,SD SIOUX FALLS (ENVIRON. CANADA),NaN,US,SD
52608,US10RMHS145,40.5268,-105.1113,1569.1,CO RMHS 1.6 SSW,NaN,US,CO
52609,US10adam001,40.5680,-98.5069,598.0,NE JUNIATA 1.5 S,NaN,US,NE
52610,US10adam002,40.5093,-98.5493,601.1,NE JUNIATA 6.0 SSW,NaN,US,NE
52611,US10adam003,40.4663,-98.6537,615.1,NE HOLSTEIN 0.1 NW,NaN,US,NE
52612,US10adam004,40.4798,-98.4026,570.0,NE AYR 3.5 NE,NaN,US,NE
52613,US10adam006,40.4372,-98.5912,601.1,NE ROSELAND 2.8 SW,NaN,US,NE
52614,US10adam007,40.5389,-98.4713,588.9,NE HASTINGS 5.4 WSW,NaN,US,NE
52615,US10adam008,40.4953,-98.2973,566.9,NE GLENVIL 2.3 WSW,NaN,US,NE
52616,US10adam010,40.5532,-98.6297,622.1,NE JUNIATA 6.9 WSW,NaN,US,NE
52617,US10adam011,40.4078,-98.6161,593.1,NE ROSELAND 5.2 SW,NaN,US,NE
52618,US10adam012,40.6200,-98.3900,588.9,NE HASTINGS 2.3 N,NaN,US,NE
52619,US10adam013,40.6600,-98.4200,598.0,NE HASTINGS 5.3 NNW,NaN,US,NE
52620,US10adam015,40.6258,-98.7034,632.2,NE KENESAW 2.4 W,NaN,US,NE
52621,US10adam016,40.6400,-98.3949,598.0,NE HASTINGS 3.7 N,NaN,US,NE

In [30]:
stn['COUNTRY_CODE'].unique()

array(['US'], dtype=object)

In [31]:
def find_digit_pos(name):
    try:
        position = re.search(r"\d",name)
        return name[0:position.start()]
    except:
        return name[0:len(name)]

In [32]:
# stn.loc[stn['NAME']=='NE HASTINGS 5.3 NNW'z

In [33]:
stn["STATE_CITY_NAME"] = stn.apply(lambda row: find_digit_pos(row['NAME']),axis=1)

In [34]:
stn.head()

,STATION,LAT,LONG,ELEV,NAME,ZIP,COUNTRY_CODE,STATE_CODE,STATE_CITY_NAME
52607,US009052008,43.7333,-96.6333,482.0,SD SIOUX FALLS (ENVIRON. CANADA),NaN,US,SD,SD SIOUX FALLS (ENVIRON. CANADA)
52608,US10RMHS145,40.5268,-105.1113,1569.1,CO RMHS 1.6 SSW,NaN,US,CO,CO RMHS
52609,US10adam001,40.5680,-98.5069,598.0,NE JUNIATA 1.5 S,NaN,US,NE,NE JUNIATA
52610,US10adam002,40.5093,-98.5493,601.1,NE JUNIATA 6.0 SSW,NaN,US,NE,NE JUNIATA
52611,US10adam003,40.4663,-98.6537,615.1,NE HOLSTEIN 0.1 NW,NaN,US,NE,NE HOLSTEIN

In [36]:
stn.to_parquet('stn.parquet')